server:
  config:
    persistence:
      default:
        driver: "sql"

        sql:
          driver: "mysql8"
          host: temporal-mysql
          port: 3306
          database: temporal
          user: root
          password: temporalRoot
          maxConns: 20
          maxIdleConns: 20
          maxConnLifetime: "1h"

cassandra:
  enabled: false

mysql:
  enabled: true
  auth:
    rootPassword: temporalRoot

postgresql:
  enabled: false

schema:
  createDatabase:
    enabled: true
  setup:
    enabled: true
  update:
    enabled: true

prometheus:
  enabled: false

grafana:
  enabled: false

elasticsearch:
  enabled: true
  replicas: 1

